# -*- coding: utf-8 -*-
"""student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10idx29pOofQ-RXQP0vrhtS4_31mT8yfG
"""

import pandas as pd
import numpy as np

import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("StudentsPerformance.csv")

print(df.head())

print(df.columns)

print(df.isnull().sum()) #Check for missing values

df = df.dropna() #Remove missing values (if any)

print(df.isnull().sum())

df["Result"] = df["math score"].apply(lambda x: "Pass" if x >= 40 else "Fail")

print(df.head()) #Create Target Column (Result)

#Encode Categorical Data Convert text columns into numbers.

from sklearn.preprocessing import LabelEncoder


encoder = LabelEncoder()

categorical_columns = [
    'gender',
    'race/ethnicity',
    'parental level of education',
    'lunch',
    'test preparation course',
    'Result'
]

for col in categorical_columns:
    df[col] = encoder.fit_transform(df[col])

print(df.head())

'''Select X and Y
X = Features
Y = Target'''

X = df.drop("Result", axis=1)

y = df["Result"]

print(X.head())
print(y.head())

#Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

#StandardScaler (Needed for KNN)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

#Apply KNN Algorithm
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

#KNN Prediction
y_pred_knn = knn.predict(X_test)

print(y_pred_knn)

#KNN Accuracy
from sklearn.metrics import accuracy_score

knn_accuracy = accuracy_score(y_test, y_pred_knn)

print("KNN Accuracy =", knn_accuracy)

#KNN Confusion Matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_knn)

print(cm)

#KNN Classification Report
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_knn))

#Apply Decision Tree
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

#Decision Tree Prediction
y_pred_dt = dt.predict(X_test)

print(y_pred_dt)

#Decision Tree Accuracy
dt_accuracy = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy =", dt_accuracy)

#Decision Tree Confusion Matrix
cm = confusion_matrix(y_test, y_pred_dt)

print(cm)

#Decision Tree Classification Report
print(classification_report(y_test, y_pred_dt))

#Compare Both Algorithms

print("KNN Accuracy :", knn_accuracy)
print("Decision Tree Accuracy :", dt_accuracy)

if knn_accuracy > dt_accuracy:
    print("KNN performs better on this dataset.")
elif dt_accuracy > knn_accuracy:
    print("Decision Tree performs better on this dataset.")
else:
    print("Both algorithms have the same accuracy.")